### ISSUE TITLE
Can Triplo run on Raspberry Pi?

### ISSUE THREAD

**Issue by bukit-kronik** [Elbruz-Technologies/triplo#1]
Need distro recommendations and hardware requirements please..

**Comment by sami-azzam** [comment]
Hey Bukit, 
Sorry I didn't notice your question.

Raspberry Pi is based on ARM architecture and we currently only build for x86 on Linux.

If you have a suitable use case that is best for Raspberry Pi, please let me know about it and I'll check with the team it's feasible to compile an ARM64 Linux version.

Cheers.
